services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD:-Pass123!}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  app:
    build: ./SensorApp
    environment:
      ConnectionStrings__SensorDb: "Server=db,1433;Database=sdb;User Id=sa;Password=${SA_PASSWORD:-Pass123!};TrustServerCertificate=True;"
      ConnectionStrings__MasterDb: "Server=db,1433;Database=master;User Id=sa;Password=${SA_PASSWORD:-Pass123!};TrustServerCertificate=True;"
    ports:
      - "5001:8080"
    depends_on:
      - db

volumes:
  sqldata:
